apiVersion: v1
kind: Secret
metadata:
  name: finance-digest-secret
  labels:
    app: finance-digest
type: Opaque
stringData:
  FINNHUB_API_URL: <FINNHUB_API_URL>
  FINNHUB_API_KEY: <FINNHUB_API_KEY>