apiVersion: v1
kind: Secret
metadata:
  name: finance-digest-secret
  labels:
    app: finance-digest
type: Opaque
stringData:
  NEXT_PUBLIC_FINNHUB_API_URL: <NEXT_PUBLIC_FINNHUB_API_URL>
  NEXT_PUBLIC_FINNHUB_API_KEY: <NEXT_PUBLIC_FINNHUB_API_KEY>